namespace: dev
replicas:
  - name: petclinic-demo
    count: 3
images:
- name: MYAPP-IMAGE
  newName: jingood2/petclinic-demo
  newTag: 2d42b5fd9859ffa6299a60a4e747148f4b91efe8
resources:
- ../../base
- namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
